add timeout checks to mkinitcpio hook

diff --git a/overlays/server-os-arch-mkinitcpio/etc/initcpio/hooks/stiefel b/overlays/server-os-arch-mkinitcpio/etc/initcpio/hooks/stiefel
--- a/overlays/server-os-arch-mkinitcpio/etc/initcpio/hooks/stiefel
+++ b/overlays/server-os-arch-mkinitcpio/etc/initcpio/hooks/stiefel
@@ -85,6 +85,11 @@ while [ $i -lt 1000 ]; do
   i=$(($i+1))
 done
 
+if [ $i == 1000 ]; then
+  echo "Failed to setup interface"
+  exit 1
+fi
+
 ip link set up stiefellink
 
 echo "waiting for server to be reachable"
@@ -97,6 +102,11 @@ while [ $i -lt 500 ]; do
   sleep 0.1
   i=$(($i+1))
 done
+
+if [ $i == 500 ]; then
+  echo "Failed to reach wireguard server at $wgserver on port $wgport"
+  exit 1
+fi
 
 ip link add dev wgstiefel type wireguard
 
@@ -122,6 +132,11 @@ while [ $i -lt 30 ]; do
   sleep 0.1
   i=$(($i+1))
 done
+
+if [ $i == 30 ]; then
+  echo "Failed to reach nbd server at $nbdserver via wireguard"
+  exit 1
+fi
 
 echo "modprobe nbd"
 modprobe nbd
